name: CI

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6

    - name: Install Nix
      uses: cachix/install-nix-action@8aa03977d8d733052d78f4e008a241fd1dbf36b3  # v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          auto-optimise-store = true
          experimental-features = nix-command flakes

    - name: Check Nix flake
      run: nix flake check

    - name: Build Nix flake
      run: nix build

    - name: Check README formatting
      run: nix develop -c prettier --check README.md renovate.json

    - name: Check YAML formatting
      run: nix develop -c yamllint .github/workflows/ci.yml

    - name: Check Nix formatting
      run: nix develop -c alejandra --check flake.nix home-manager.nix package.nix

    - name: Check Ruff
      run: nix develop -c ruff check

    - name: Check pytest
      run: nix develop -c pytest

    - name: Check Pyright
      run: nix develop -c pyright

    - name: Lint info.plist
      run: nix develop -c plistutil -i info.plist -f xml -o /dev/null

    - name: Lint version.plist
      run: nix develop -c plistutil -i version.plist -f xml -o /dev/null

    - name: Lint localized info plist strings
      run: nix develop -c plistutil -i resources/english.lproj/info_plist.strings -f xml -o /dev/null

    - name: Check ty
      run: nix develop -c ty check .

    - name: Check pyupgrade
      run: |
        nix develop -c pyupgrade --py314-plus scripts/*.py
        git diff --exit-code
